config/routes.rb
Rails.application.routes.draw do
  resources :products 

  resources :carts do
    resources :cartships
    # member do
    #   post :pay
    #   post :remove_item
    # end
  end

  get 'sales/index'

  root 'sales#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cartships, dependent: :destroy
  has_many :products, through: :cartships

  def total_price
    cartships.map { |cartship| cartship.quantity * cartship.product.price }.sum
  end
end

app/models/cartship.rb
class Cartship < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    # @cart = Cart.new
    Cart.create status: "pending"
    redirect_to new_cart_cartship_path(Cart.first, product_id: Product.first)
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:status)
    end
end

app/controllers/cartships_controller.rb
class CartshipsController < ApplicationController
  before_action :set_cart
  before_action :set_cartship, only: [:show, :edit, :update, :destroy]

  # GET /cartships
  # GET /cartships.json
  def index
    @cartships = @cart.cartships.all
  end

  # GET /cartships/1
  # GET /cartships/1.json
  def show
  end

  # GET /cartships/new
  def new
    @quantity = 1
    @cartship = @cart.cartships.new
  end

  # GET /cartships/1/edit
  def edit
    @quantity = @cartship.quantity
  end

  # POST /cartships
  # POST /cartships.json
  def create
    # raise "#{cartship_params}"
    @cartship = @cart.cartships.new(cartship_params)

    # raise "#{cartship_params}"
    respond_to do |format|
      if @cartship.save
        
        format.html { redirect_to root_url, notice: 'Cartship was successfully created.' }
        format.json { render :show, status: :created, location: @cartship }
      else
        format.html { render :new }
        format.json { render json: @cartship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartships/1
  # PATCH/PUT /cartships/1.json
  def update
    respond_to do |format|
      if @cartship.update(cartship_params)
        format.html { redirect_to cart_cartships_url, notice: 'Cartship was successfully updated.' }
        format.json { render :show, status: :ok, location: @cartship }
      else
        format.html { render :edit }
        format.json { render json: @cartship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartships/1
  # DELETE /cartships/1.json
  def destroy
    @cartship.destroy
    respond_to do |format|
      if @cart.cartships.any?
        format.html { redirect_to cart_cartships_url, notice: 'Cartship was successfully destroyed.' }
      else
        format.html { redirect_to root_url, notice: 'Cartship was successfully destroyed.' }        
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.first
    end

    def set_cartship
      @cartship = @cart.cartships.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cartship_params
      params.require(:cartship).permit(:cart_id, :product_id, :quantity)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    @products = Product.order(:title).to_a
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td>
          <%= link_to cart.status, cart %>
        </td>
        <td><%#= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= button_to 'sepeti sil', @cart, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button success' %>

<table>
  <thead>
    <tr>
      <th>ürün</th>
      <th>adet</th>
      <th>birim fiyatı</th>
      <th>toplam fiyatı</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart.cartships.each do |cartship| %>
      <tr>
        <td>
          <%= cartship.product.title %>
        </td>
        <td>
          <%= cartship.quantity %>
        </td>
        <td>
          <%= cartship.product.price %>
        </td>
        <td>
          <%= cartship.product.price * cartship.quantity %>          
        </td>
        <td>
          <%= link_to 'sepetten çıkar', cartship, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cartships/_form.html.erb
<%= simple_form_for([@cart, @cartship]) do |f| %>
    <h3>
      <% if @cartship.product.present? %>
        <%= @cartship.product.title  %>
        <%= f.hidden_field :product, value: @cartship.product %>
      <% else %>
        <%= Product.find(params[:product_id]).title %>
        <%= f.hidden_field :product_id, value: params[:product_id] %>
      <% end %>
    </h3>

    <%= f.hidden_field :cart_id, value: @cart.id %>
    

    <%= f.input :quantity, autofocus: true, label: false, :input_html => { :type => "number", :value => @quantity } %>

    <%= f.button :submit %>
<% end %>

app/views/cartships/edit.html.erb
<h1>Editing Cartship</h1>

<%= render 'form', cartship: @cartship %>

app/views/cartships/index.html.erb
<p id="notice"><%= notice %></p>

<%= button_to 'sepeti sil', @cart, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button success' %>

<h1>Cartships</h1>

<table>
  <thead>
    <tr>
      <th>ürün</th>
      <th>adet</th>
      <th>birim fiyatı</th>
      <th>toplam fiyatı</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartships.each do |cartship| %>
      <tr>
        <td><%= cartship.product.title %></td>
        <td><%= cartship.quantity %></td>
        <td><%= cartship.product.price %></td>
        <td>
          <%= cartship.product.price * cartship.quantity %>          
        </td>        
        <td><%= link_to 'güncelle', edit_cart_cartship_path(@cart, cartship) %></td>
        <td><%= link_to 'sepetten çıkar', cart_cartship_path(@cart, cartship), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<h5>toplam: </h5>
<h6 class="subheader">
  <%= @cart.total_price  %>
</h6>

app/views/cartships/new.html.erb
<h1>New Cartship</h1>

<%= render 'form', cartship: @cartship %>

<%#= link_to 'Back', cartships_path %>

app/views/cartships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cart:</strong>
  <%= @cartship.cart %>
</p>

<p>
  <strong>Product:</strong>
  <%= @cartship.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cartship.quantity %>
</p>

<%= link_to 'Edit', edit_cartship_path(@cartship) %> |
<%= link_to 'Back', cartships_path %>

app/views/layouts/_navigation.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="menu">
      <li>
        <%= link_to 'Ana Sayfa', root_path %>
      </li>
      <li>
        <%= link_to 'Ürünler', products_path %>
      </li>

    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li>
        <%#= link_to "Sepet (#{Cart.first.cartships.count})", cart_path(Cart.first) if Cart.any? %>
        <%= link_to "Sepet (#{Cart.first.cartships.count})", cart_cartships_url(Cart.first) if Cart.any? %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation'  %>
    <%= yield %>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= link_to product.title, product %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <!-- <td> -->
          
          <%#= link_to 'Add to Cart', add_to_cart_product_path(product)  %>
          
        <!-- </td> -->

        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Satış</h1>

<table>
  <thead>
    <tr>
      <th>Ürün</th>
      <th>Fiyat</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <% if Cart.any? %>
            <% if Cartship.any? && Cartship.find_by(product_id: product) %>
                <%= link_to 'add to cartship: update item', edit_cart_cartship_path(Cart.first, Cartship.all.find_by(product_id: product)) %>  
            <% else %>
              <%= link_to 'add to cartship: new item', new_cart_cartship_path(Cart.first, product_id: product) %>
            <% end %>
          <% else %>
            <%= link_to 'add to cart', new_cart_path %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>